// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsj48kjzUMrIFkzigFurej2E7VjQzQbDg',
    appId: '1:833889707400:web:5a601483f5c9802e64063d',
    messagingSenderId: '833889707400',
    projectId: 'car-rental-hadi-2026',
    authDomain: 'car-rental-hadi-2026.firebaseapp.com',
    storageBucket: 'car-rental-hadi-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-ky-jGIcmf_WUJgla4kBEyjOWbMK080',
    appId: '1:833889707400:android:f94916ffa3a9178264063d',
    messagingSenderId: '833889707400',
    projectId: 'car-rental-hadi-2026',
    storageBucket: 'car-rental-hadi-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_wawQiDP-R3QNgrqoTAuvkYhbkP2FmY',
    appId: '1:833889707400:ios:4b5458b2ea8eb10f64063d',
    messagingSenderId: '833889707400',
    projectId: 'car-rental-hadi-2026',
    storageBucket: 'car-rental-hadi-2026.firebasestorage.app',
    iosBundleId: 'com.example.carRentalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_wawQiDP-R3QNgrqoTAuvkYhbkP2FmY',
    appId: '1:833889707400:ios:4b5458b2ea8eb10f64063d',
    messagingSenderId: '833889707400',
    projectId: 'car-rental-hadi-2026',
    storageBucket: 'car-rental-hadi-2026.firebasestorage.app',
    iosBundleId: 'com.example.carRentalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsj48kjzUMrIFkzigFurej2E7VjQzQbDg',
    appId: '1:833889707400:web:deb9fee1226bc8ce64063d',
    messagingSenderId: '833889707400',
    projectId: 'car-rental-hadi-2026',
    authDomain: 'car-rental-hadi-2026.firebaseapp.com',
    storageBucket: 'car-rental-hadi-2026.firebasestorage.app',
  );
}
